name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          # submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify -b "https://studentweb.uvic.ca/~zhangyichi"
        # run: hugo --gc --minify -b $URL

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.TOKEN }}
      #     external_repository: <username>/<username>.github.io
      #     publish_dir: ./public
      #     #   keep_files: true
      #     user_name: <username>
      #     user_email: <username@email.com>
      #     publish_branch: master
      #   #   cname: example.com


      - name: Develop
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:MrZhangCSU/hugo-website-compiled-zyc.git
          BRANCH: master
          FOLDER: public
          SSH_PRIVATE_KEY: ${{ secrets.PUBLISH_TOKEN }}